services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vayonis
      POSTGRES_PASSWORD: vayonis
      POSTGRES_DB: vayonis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A app.workers.celery_app worker --loglevel=info
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  beat:
    build: .
    command: celery -A app.workers.celery_app beat --loglevel=info
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
     

volumes:
  pgdata:
